version: '2'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
  engine:
    build: ./engine
    ports:
      - "10001:80"
    environment:
      - PORT=80
      - MONGO_SHARD_URL_one=mongodb://db:27017/apm
      - MONGO_URL=mongodb://db:27017/apm
    links:
      - db
  rma:
    build: ./rma
    environment:
      - MONGO_SHARD=one
      - MONGO_URL=mongodb://db:27017/apm
    links:
      - kadira-db
  api:
    build: ./api
    ports:
      - "10002:80"
    environment:
      - PORT=80
      - MONGO_APP_URL=mongodb://db:27017/apm
      - MONGO_SHARD_URL_one=mongodb://db:27017/apm
      - MAIL_URL=smtp://user:pass@smtp.mailgun.org:587
    links:
      - db
  ui:
    build: ./ui
    ports:
      - "10003:80"
    environment:
      - PORT=80
      - ROOT_URL=http://127.0.0.1:10003
      - MONGO_URL=mongodb://db:27017/apm
      - MONGO_SHARD_URL_one=mongodb://db:27017/apm
      - MAIL_URL=smtp://user:pass@smtp.mailgun.org:587
      - METEOR_SETTINGS={"public":{}}
    links:
      - db
